apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where all resources are deployed.
namespace: kubeflow-system
sortOptions:
  order: fifo

resources:
  - namespace.yaml
  - ../../third-party/jobset  # Comment this line if JobSet is installed on the Kubernetes cluster.
  - ../../base/crds
  - ../../base/runtimes
  - ../../base/manager
  - ../../base/rbac
  - ../../base/webhook

# Update the Kubeflow Trainer controller manager image tag.
images:
  - name: kubeflow/trainer-controller-manager
    newTag: latest

# Secret for the Kubeflow Training webhook.
secretGenerator:
  - name: kubeflow-trainer-webhook-cert
    namespace: kubeflow-system
    options:
      disableNameSuffixHash: true
